package dev.claudefleet.mobile.model

import dev.claudefleet.mobile.net.json
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * The phone's standup is the desktop's, byte for byte.
 *
 * Every case in `fixtures/today-standup.json` — generated by running
 * claude-fleet's `src/lib/today.ts` — goes through [scopeToday] and
 * [standupText] here, and must come out exactly as the desktop's did. The file
 * is wrapped into [TODAY_STANDUP_FIXTURE] at build time, so this runs on
 * Kotlin/Native too.
 *
 * The desktop scopes by a string id (`all`, `org:<id>`, `owner:<name>`,
 * `unassigned`); the phone's filter is an org or nothing, so `all` is null and
 * `org:<id>` is that id. A case scoped some other way has no phone equivalent
 * and is skipped, by name, below.
 */
class StandupFixtureTest {

    @Serializable
    private data class Fixture(val cases: List<Case>)

    @Serializable
    private data class Case(
        val name: String,
        val today: Today,
        val scope: String,
        /** A session id → the desktop scope of its live row; absent means no live row. */
        @SerialName("scope_of") val scopeOf: Map<String, String> = emptyMap(),
        val standup: String,
        val sections: Sections,
    )

    @Serializable
    private data class Sections(
        val waiting: List<String?>,
        @SerialName("in_progress") val inProgress: List<String?>,
        val shipped: List<String?>,
        val stale: List<String?>,
    )

    private val fixture = json.decodeFromString(Fixture.serializer(), TODAY_STANDUP_FIXTURE)

    /** The desktop scope id as the phone's org filter; null for a scope the phone cannot express. */
    private fun orgOf(scope: String): Long? = scope.removePrefix("org:").takeIf { it != scope }?.toLongOrNull()

    /** The cases the phone's filter can express, each with its org (null for `all`) and its view. */
    private val phoneCases: List<Pair<Case, TodayView>> = fixture.cases.mapNotNull { case ->
        val org = if (case.scope == "all") null else orgOf(case.scope) ?: return@mapNotNull null
        // A session's org is its live row's; one with no row, or a row the
        // desktop places by owner, belongs to no org.
        case to scopeToday(case.today, org) { s -> case.scopeOf[s.id.toString()]?.let(::orgOf) }
    }

    @Test
    fun the_fixture_is_there_and_covers_every_section() {
        assertTrue(fixture.cases.size >= 7, "the fixture has lost its cases")
        val skipped = fixture.cases.map { it.name } - phoneCases.map { it.first.name }.toSet()
        assertEquals(listOf("a scope with nothing in it"), skipped, "only the owner-scoped case has no phone equivalent")
        val all = phoneCases.first { it.first.scope == "all" && it.first.standup.startsWith("Shipped") }.first
        for (section in listOf("Shipped", "In progress", "Waiting on me", "Stale")) {
            assertTrue("$section\n" in all.standup, "no case exercises $section")
        }
        assertTrue(phoneCases.any { it.first.scope.startsWith("org:") }, "no case exercises an org filter")
    }

    @Test
    fun every_case_formats_exactly_as_the_desktop_did() {
        for ((case, view) in phoneCases) {
            assertEquals(case.standup, standupText(view), "standup for \"${case.name}\"")
        }
    }

    @Test
    fun every_case_sorts_into_the_desktop_sections() {
        for ((case, view) in phoneCases) {
            val got = Sections(
                waiting = view.waiting.map { it.key },
                inProgress = view.inProgress.map { it.key },
                shipped = view.shipped.map { it.key ?: it.prUrl },
                stale = view.stale.map { it.key },
            )
            assertEquals(case.sections, got, "sections for \"${case.name}\"")
            assertEquals(case.standup == "Nothing to report.\n", view.isEmpty, "emptiness for \"${case.name}\"")
        }
    }
}
